// <auto-generated />
using System;
using Aimrank.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aimrank.Database.Migrator.Migrations
{
    [DbContext(typeof(AimrankContext))]
    partial class AimrankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Aimrank.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoreCT")
                        .HasColumnType("int");

                    b.Property<int>("ScoreT")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches", "aimrank");
                });

            modelBuilder.Entity("Aimrank.Domain.Matches.Match", b =>
                {
                    b.OwnsMany("Aimrank.Domain.Matches.MatchPlayer", "Players", b1 =>
                        {
                            b1.Property<string>("SteamId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Assists")
                                .HasColumnType("int");

                            b1.Property<int>("Deaths")
                                .HasColumnType("int");

                            b1.Property<int>("Kills")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<int>("Score")
                                .HasColumnType("int");

                            b1.Property<int>("Team")
                                .HasColumnType("int");

                            b1.HasKey("SteamId", "MatchId");

                            b1.HasIndex("MatchId");

                            b1.ToTable("MatchesPlayers", "aimrank");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
