fragment LobbyFields on Lobby {
  id
  status
  match {
    id
    map
    mode
    status
    address
  }
  configuration {
    maps
    mode
    name
  }
  members {
    isLeader
    user {
      id
      username
    }
  }
}