#import "./TeamPlayer.gql"

query getMatchesView($userId: Uuid! $mode: Int!) {
  matches(filter: {playerId: $userId mode: $mode} take: 20) {
    nodes {
      id
      map
      mode
      scoreT
      scoreCT
      winner
      teamTerrorists {
        ...TeamPlayer
      }
      teamCounterTerrorists {
        ...TeamPlayer
      }
      createdAt
      finishedAt
    }
  }
  user(userId: $userId) {
    stats {
      matchesTotal
      matchesWon
      totalHs
      totalKills
      totalDeaths
    }
  }
}