version: "3.5"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Secret123!
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
        
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
