version: "3.5"

services:
  web:
    image: aimrank:latest
    ports:
      - 80:80
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - mssql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3.8.9-management
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    image: redis:6.0.10-alpine

volumes:
  mssql_data:
