version: "3.5"

services:
  web:
    build: ..
    environment:
      - ConnectionStrings__Database=Server=db;Database=Aimrank;User=sa;Password=Secret123!
    volumes:
      - ../src/Aimrank.Web.App/wwwroot:/home/app/wwwroot
  
  db:
    environment:
      - SA_PASSWORD=Secret123!
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
  
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    ports:
      - 6379:6379
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
