version: "3.5"

services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Secret123!
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
